### ISSUE TITLE
Organizacija podatkov

### ISSUE THREAD

**Issue by andrejbauer** [kastelecn/Skokci#4]
### Razred `GUI`

* kaj se zgodi v `__init__`:
   * kako GUI nariše krogce? V zanki `for k in range(28)` jih narišemo na ustreznih mestih in si spravljamo v `self.polja` pare `((x,y), g)`, kot je to opisano spodaj. Kakšen krogec moramo narisati pri danem `k` izvemo od `self.igra.tip_polja(k)`.
   * kako GUI nariše črte med polji? Gre po `Igra.POVEZAVE` in dobi krajišča črt s pomočjo `self.
   * naredi zajce in lisice in spravi njihove GIDje v `self.zajci` in `self.lisice`. Začetne pozicije zajcev in lisic? Lahko jih damo na poljubne koordinate, in nato takoj pokličemo `narisi_pozicijo` (pozor, `narisi_pozicijo` se zanaša, da že imamo pravilno nastavljen `self.igra`)
* atribut `self.igra`: objekt, ki predstavlja (logično) stanje igre
* atribut `self.plosca`: `tkinter.Canvas`
* atribut `self.polja` : seznam elementov `((x,y), g)` in sicer `self.polja[k] = ((x,y), g)`, kjer je `k` indeks polja, `(x,y)` njegove koodinate na zaslonu (središče) in `g` je GID krogca za to polje
* atribut `self.polja_zajci`: seznam elementov `(x,y)` in sicer koordinate, kjer čakajo zajci izven plošče
* atribut `self.polja_lisice`: seznam elementov `(x,y)` in sicer koordinate, kjer čakajo lisice izven plošče
z indeksom `k` izvemo od `Igra.tip_polja`.
* atribut `self.lisice`: seznam grafičnih IDjev krogcev, ki predstavljajo lisice
* atribut `self.zajci`: seznam grafičnih IDjev krogcev, ki predstavljajo zajce
* metoda `narisi_pozicijo`: postavi vse figure na `self.plosca` tja, kjer morajo biti:

       i = 0
       na_plosci = len(self.igra.zajci):
       while i < na_plosci:
          self.zajci[i] premakni na polje z indeksom self.igra.zajci[i]
          i += 1
      while i < len(self.zajci):
         self.zajci[i] premakni izven plošče na mesto i - len_plosci

* klikanje uporabnika: vedeti moramo, ali izbiramo figuro ali prestavljamo že izbrano figuro. Imamo atribut `self.oznacen` z vrednostjo:
   * `None`, če smo v fazi izbiranja figure
   * če je figura že izbrana, imamo v `self.oznacen` eno od vrednosti, ki jih vrne `self.kliknjeno_polje` (razen `None` in `(POLJE, k)`)
* metoda `kliknjeno_polje(x,y)`: podamo koordinate na zaslonu (dobili jih bomo od klika iz `event.x` in `event.y`) in vrnemo, kaj stoji tam stoji:
    * tam ni ničesar zanimivega: vrnemo `None`
    * tam je zajec izven plošče: vrnemo `CAKAJOCI_ZAJEC`
    * tam je lisica izven plošče: vrnemo `CAKAJOCA_LISICA`
    * tam je prazno polje z indeksom `k`: vrnemo `(POLJE, k)`
    * tam je zajec na plošči in sicer na polju z indeksom `k`: `(ZAJEC, k)`
    * tam je lisica na plošči in sicer na polju z indeksom `k`: `(LISICA, k)`

   Kako izvemo, katera od možnosti se je zgodila? S pomočjo `self.polja`, `self.polja_zajci` in `self.polja_lisice` lahko ugotovimo, ali je uporabnik kliknil na "zanimivo lokacijo". Glede na to, kam je kliknil lahko potem ugotovimo, na kaj je kliknil.

### Razred `Igra`

* vsako polje na plošči ima svoj **indeks polja**, ki je število od `0` do `27`
* konstanta `Igra.POVEZAVE`: seznam povezav med polji, pari `(i,j)`, za povezavo od polja z indeksom `i` do polja z indeksom `j`. Dogovor: *vedno* je `i < j`.
* metoda `tip_polja(k)`: vrne, kakšnega tipa je polje z indeksom `k`. Možni odgovori: `VSTOPNO_ZAJEC`, `VSTOPNO_LISICA`, `NAVADNO`, `ZMAGOVALNO_ZAJEC`, `ZMAGOVALNO_LISICA`
* Stanje igre:
   1. atribut `self.na_potezi`: vrednosti so `LISICA`, `ZAJEC` ali `None`, če je igre konec
   2. atribut `self.lisice`: seznam indeksov polj, na katerih so lisice (največja dolžina je 5)
   3. atribut `self.zajci`: seznam indekov polj, na katerih so zajci (največja dolžina 5)

   Opomba: zunaj plošče čaka `5 - len(self.lisice)` lisic, in podobno za zajce.

* poteza je predstavljena:
   1. s parom `(i,j)`, ki pomeni da iz polja `i` prestavimo figuro  na polje `j`. Veljavna je če: na `i` res stoji figura od tistega, ki je na potezi, `j` je sosednje polje in polje `j` je prazno.
   2. s parom `('CAKALNICA`, i)`, ki pomeni da iz čakajočih postavimo eno figuro na polje `i`: Veljavna je, če: `self.tip_polja(i)` pravi, da je to vstopno polje za tistega, ki je na potezi in to polje je prazno, in zares imamo koga v čakalnici
* kako izvedemo potezo:
   1. preverimo, ali je poteza dovoljena (glej opis zgoraj), če ni dovoljena vrnemo `None`
   2. če je dovoljena, popravimo `self.lisice` in `self.zajci` (lahko se spremenita oba, če smo koga ujeli)
   3. ugotovimo, kakšno je novo stanje igre:
      * če igre ni konec, popravimo `self.na_potezi` na nasprotnika in vrnemo `NI_KONEC`
      * če je igre konec, popravimo `self.na_potezi` na `None` in vrnemo zmagovalca
* kako ugotovimo, stanje igre: če je lisica na zmagovalnem polju za lisice, vrnemo `LISICA`, podobno preverimo za zajce, če ni zmagovalca vrnemo `None`.
* kako ugotovimo seznam možnih potez: domača naloga

**Comment by kastelecn** [comment]
Closed with commit e996ace

**Comment by kastelecn** [comment]
Urejeno: commit e996ace
